apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - image: rayeez/k8s-config-secrets:v1
          name: my-config-secrets
      imagePullSecrets:
        - name: docker-pwd

