apiVersion: v1
kind: Secret
metadata:
  name: aws-creds-in-file
type: Opaque
stringData:
  # pasting keys as it is because we are mounting it on a volume, encryption wont work here
  credentials: |
    [default]
    aws_access_key_id =    
    aws_secret_access_key = 
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod-1
spec:
  containers:
    - name: aws-cli-container
      image: rayeez/troubleshootingtools:v2
      volumeMounts:
        - name: secret-volume
          mountPath: /root/.aws/credentials
          subPath: credentials
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: aws-creds-in-file
